version: '3'

services:
  mysql-master:
    image: 'syphdig/mysql-bitnami:0407'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    deploy:
      placement:
        constraints: [node.hostname == dev1]

  mysql-slave:
    image: 'syphdig/mysql-bitnami:0407'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=slave_root_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    deploy:
      placement:
        constraints: [node.hostname == dev1]

