FROM registry.cn-qingdao.aliyuncs.com/syph-infra/ansible:latest 
WORKDIR /tmp
#COPY  .  /tmp

#RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa

# ==> Creating inventory file...
# RUN echo localhost > inventory

# ==> Executing Ansible...
#RUN ansible-playbook -i inventory publish.yml --connection=local --sudo


